### ISSUE TITLE
FA1: The player should be able create and join an online multiplayer game 

### ISSUE THREAD

**Issue by cherrybeans** [Gullskatten/beardblaster#1]
The player should be able create and join an online multiplayer game 

- [x] PlayerB should be able to enter a game-id
- [x] PlayerA should be able to create a joinable game-id
- [x] The game should have create and join buttons
- [x] Set up Firestore
- [x] Define game/lobby fields
- [x] PlayerB should be notified when entering a invalid game-id
- [x] PlayerA should be notified when playerB joins the game
