### ISSUE TITLE
FA6: The player should be able to cast spells at the opponent 

### ISSUE THREAD

**Issue by cherrybeans** [Gullskatten/beardblaster#2]
- [x] Communication with firestore #46 
- [x] The players need to be able to choose elements #35 
- [x] The game provides spell information #49 
- [x] Animation of spellcasting #36 
- [x] Damage indicators
- [x] The player should be able to clear chosen elements #35 
- [x] The player should be able to lock chosen elements #49
