### ISSUE TITLE
The player loses HP if it gets hit by a spell from the opponent 

### ISSUE THREAD

**Issue by cherrybeans** [Gullskatten/beardblaster#5]
- [x] If you loose all your health the game ends
- [x] The players need health #40 
- [x] The players health updates based on which spells were casted
- [x] HP should be visualized with a health bar
