### ISSUE TITLE
The players should have a common, limited preparation time to choose their action 

### ISSUE THREAD

**Issue by cherrybeans** [Gullskatten/beardblaster#8]
- [x] The game needs a world timer #39 
- [x] The countdown timer starts at each round #39 
- [x] If both players have their spells locked, the preparation state ends
- [x] Waiting screen
- [x] If the player has not locked in three elements when preparation state ends, no spells are cast
